name: Build and Upload JAR to GitHub Releases

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/QA-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    defaults:
      run:
        working-directory: source/did-orchestrator-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test
        run: ./gradlew test

      - name: Build JAR
        run: |
          ./gradlew bootjar
          echo "JAR file generated at:"
          find ./build/libs -name "*.jar"

      - name: Set release title
        id: set_release_title
        run: |
          release_tag=${GITHUB_HEAD_REF#release/QA-}
          release_tag_upper="V$release_tag"
          echo "Release tag: $release_tag_upper"
          echo "Raw tag for filename: $release_tag"
          echo "release_tag_upper=$release_tag_upper" >> $GITHUB_OUTPUT
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT

      - name: Extract changelog entry
        id: changelog
        run: |
          version_tag=${{ steps.set_release_title.outputs.release_tag }}
          echo "Extracting changelog for version: $version_tag"
          changelog=$(awk "/^## $version_tag/ {flag=1; next} /^## / {flag=0} flag" CHANGELOG.md)
          changelog_cleaned=$(echo "$changelog" | sed '/^\s*$/d')
          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
          echo "$changelog_cleaned" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
	  
      - name: Get commit messages
        id: get_commit_messages
        run: |
          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"* %s")
          echo "$commits" > commit_messages.txt
          echo "commits=$commits" >> $GITHUB_OUTPUT

      - name: Find JAR file
        id: find_jar
        run: |
          jar_path=$(find ./build/libs -name "*.jar" | head -n 1)
          echo "jar_path=$jar_path" >> $GITHUB_OUTPUT

      - name: Calculate SHA-256
        id: calculate_sha
        run: |
          sha256=$(sha256sum ${{ steps.find_jar.outputs.jar_path }} | awk '{ print $1 }')
          echo "jar_sha256=$sha256" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ steps.set_release_title.outputs.release_tag_upper }}
          release_name: ${{ steps.set_release_title.outputs.release_tag_upper }}
          body: |
            ## Changes:
            ${{ steps.get_commit_messages.outputs.commits }}
            ## Checksum:
            SHA-256: ${{ steps.calculate_sha.outputs.jar_sha256 }}

      - name: Upload JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: source/did-orchestrator-server/${{ steps.find_jar.outputs.jar_path }}
          asset_name: did-orchestrator-server-${{ steps.set_release_title.outputs.release_tag }}.jar
          asset_content_type: application/java-archive
